/** GCSE mock test catalogue — 10+ tests, 10 questions each. */

const tq = (id, topicId, text, answer, options) => ({
  id,
  topicId,
  text,
  answer,
  options,
});

const pq = (id, topicId, text, starterCode) => ({
  id,
  topicId,
  text,
  starterCode,
});

const THEORY_BANK = [
  tq("th01", "1.1", "What is the purpose of the CPU?", "To fetch, decode and execute instructions", ["To store files", "To fetch, decode and execute instructions", "To print only", "To cool the PC"]),
  tq("th02", "1.1", "Which register holds the address of the next instruction?", "Program Counter (PC)", ["ALU", "Program Counter (PC)", "MAR", "HDD"]),
  tq("th03", "1.1", "What does the ALU do?", "Arithmetic and logical operations", ["Stores files", "Arithmetic and logical operations", "Routes packets", "Displays video"]),
  tq("th04", "1.2", "Which memory is volatile?", "RAM", ["ROM", "RAM", "SSD", "Blu-ray"]),
  tq("th05", "1.2", "What is cache used for?", "Fast access to frequently used data", ["Permanent backup", "Fast access to frequently used data", "Network routing", "Printing"]),
  tq("th06", "1.2", "Which storage is typically non-volatile?", "Secondary storage (SSD/HDD)", ["RAM", "Cache", "Secondary storage (SSD/HDD)", "Registers"]),
  tq("th07", "1.3", "Which topology uses a central switch?", "Star", ["Bus", "Star", "Ring", "Line"]),
  tq("th08", "1.3", "What does IP stand for?", "Internet Protocol", ["Internal Process", "Internet Protocol", "Input Port", "Integrated Program"]),
  tq("th09", "1.3", "Which protocol is used for web pages?", "HTTP/HTTPS", ["FTP", "SMTP", "HTTP/HTTPS", "DNS"]),
  tq("th10", "1.4", "What is malware?", "Malicious software", ["Hardware fault", "Malicious software", "A type of RAM", "A network cable"]),
  tq("th11", "1.4", "What is phishing?", "Tricking users to reveal information", ["Encrypting disks", "Tricking users to reveal information", "Backing up data", "Defragmenting"]),
  tq("th12", "1.4", "Purpose of a firewall?", "Monitor and block unwanted traffic", ["Increase CPU speed", "Monitor and block unwanted traffic", "Store passwords", "Compile code"]),
  tq("th13", "2.1", "What is an algorithm?", "A step-by-step method to solve a problem", ["A programming language", "A step-by-step method to solve a problem", "A network device", "A file type"]),
  tq("th14", "2.1", "Which search is faster on sorted data?", "Binary search", ["Linear search", "Binary search", "Random search", "Manual search"]),
  tq("th15", "2.1", "What is decomposition?", "Breaking a problem into smaller parts", ["Joining problems", "Breaking a problem into smaller parts", "Deleting data", "Sorting lists"]),
  tq("th16", "2.2", "Python data type for True/False?", "Boolean", ["String", "Integer", "Boolean", "Float"]),
  tq("th17", "2.2", "Which keyword starts a function in Python?", "def", ["func", "def", "fn", "method"]),
  tq("th18", "2.2", "What does len() return?", "The length of a sequence", ["The largest number", "The length of a sequence", "The file name", "The CPU speed"]),
  tq("th19", "2.3", "Output of NOT 1?", "0", ["1", "0", "2", "Error"]),
  tq("th20", "2.3", "AND gate: 1 AND 0?", "0", ["1", "0", "2", "Undefined"]),
  tq("th21", "2.4", "How many bits in a byte?", "8", ["4", "8", "16", "32"]),
  tq("th22", "2.4", "Hex FF in denary?", "255", ["128", "255", "256", "15"]),
  tq("th23", "1.1", "What is the fetch-decode-execute cycle?", "How the CPU runs instructions", ["How RAM is cleared", "How the CPU runs instructions", "How files download", "How pixels display"]),
  tq("th24", "1.2", "Difference RAM vs ROM?", "RAM is volatile; ROM is non-volatile", ["They are identical", "RAM is volatile; ROM is non-volatile", "ROM is faster", "RAM is permanent"]),
  tq("th25", "1.3", "What is bandwidth?", "Data transferred per unit time", ["CPU clock speed", "Data transferred per unit time", "Screen resolution", "Battery life"]),
  tq("th26", "2.1", "What is abstraction?", "Hiding complexity", ["Deleting variables", "Hiding complexity", "Printing output", "Using two CPUs"]),
  tq("th27", "2.2", "Which loop runs while a condition is true?", "while", ["for only", "while", "if", "def"]),
  tq("th28", "2.4", "Why use hexadecimal?", "Compact representation of binary", ["Faster internet", "Compact representation of binary", "Encrypt passwords", "Store images"]),
  tq("th29", "1.4", "What is encryption?", "Scrambling data so only authorised users read it", ["Deleting cookies", "Scrambling data so only authorised users read it", "Sorting arrays", "Printing reports"]),
  tq("th30", "2.2", "What is a variable?", "A named storage location for data", ["A network cable", "A named storage location for data", "A CPU register only", "A printer driver"]),
  tq("th31", "1.1", "Purpose of the Control Unit?", "Coordinates CPU components", ["Stores user files", "Coordinates CPU components", "Connects Wi-Fi", "Runs Python only"]),
  tq("th32", "1.2", "What is virtual memory?", "Using disk as extra RAM", ["A video game", "Using disk as extra RAM", "A monitor setting", "A Python keyword"]),
  tq("th33", "1.3", "What is a MAC address?", "Hardware address of a network interface", ["A password", "Hardware address of a network interface", "A website URL", "A file extension"]),
  tq("th34", "2.1", "What is linear search?", "Check each item until found", ["Sort then delete", "Check each item until found", "Use binary only", "Skip half the list"]),
  tq("th35", "2.3", "OR gate: 0 OR 0?", "0", ["1", "0", "Undefined", "2"]),
  tq("th36", "1.4", "What is two-factor authentication?", "Two methods to verify identity", ["Two passwords identical", "Two methods to verify identity", "Two CPUs", "Two monitors"]),
  tq("th37", "2.2", "What is an integer?", "Whole number", ["Text", "Whole number", "True/False", "Decimal only"]),
  tq("th38", "1.3", "Client-server model means?", "Clients request; servers respond", ["No network", "Clients request; servers respond", "One shared keyboard", "No storage"]),
  tq("th39", "2.4", "What is a character set?", "Mapping numbers to characters", ["A keyboard layout only", "Mapping numbers to characters", "A monitor", "A cable type"]),
  tq("th40", "1.2", "What is cloud storage?", "Data stored on remote servers", ["Data on a floppy disk only", "Data stored on remote servers", "Data in CPU cache only", "Data in ROM only"]),
  tq("th41", "2.1", "What is a flowchart?", "Diagram showing steps and decisions", ["A Python file", "Diagram showing steps and decisions", "A network map", "A spreadsheet"]),
  tq("th42", "1.1", "Embedded system?", "Computer built into another device", ["A cloud server", "Computer built into another device", "A web browser", "A printer only"]),
  tq("th43", "2.2", "What is concatenation?", "Joining strings together", ["Splitting lists", "Joining strings together", "Deleting files", "Sorting numbers"]),
  tq("th44", "1.4", "What is a strong password?", "Long, mixed characters, hard to guess", ["Your name only", "Long, mixed characters, hard to guess", "Empty string", "Single letter"]),
  tq("th45", "2.3", "What is a truth table?", "Shows outputs for all input combinations", ["A timetable", "Shows outputs for all input combinations", "A Python list", "A network log"]),
  tq("th46", "1.3", "What is latency?", "Delay in data transfer", ["File size", "Delay in data transfer", "CPU brand", "Screen brightness"]),
  tq("th47", "2.2", "What is an array/list?", "Ordered collection of items", ["A single number", "Ordered collection of items", "A network protocol", "A keyboard"]),
  tq("th48", "1.2", "What is compression?", "Reducing file size", ["Deleting RAM", "Reducing file size", "Increasing resolution", "Adding cables"]),
  tq("th49", "2.1", "What is selection in programming?", "Choosing different paths with if/elif", ["Printing only", "Choosing different paths with if/elif", "Using only loops", "Saving files"]),
  tq("th50", "2.4", "What is binary 1010 in denary?", "10", ["8", "10", "12", "5"]),
  tq("th51", "1.1", "What is clock speed measured in?", "Hertz (Hz)", ["Bytes", "Hertz (Hz)", "Pixels", "Volts"]),
  tq("th52", "1.2", "What is defragmentation?", "Reorganising files on a disk for efficiency", ["Deleting RAM", "Reorganising files on a disk for efficiency", "Encrypting email", "Installing drivers"]),
  tq("th53", "1.3", "What does DNS do?", "Translates domain names to IP addresses", ["Prints web pages", "Translates domain names to IP addresses", "Stores passwords", "Compresses video"]),
  tq("th54", "1.4", "What is social engineering?", "Manipulating people to gain access or information", ["Writing social media apps", "Manipulating people to gain access or information", "Sorting databases", "Compiling Python"]),
  tq("th55", "2.1", "What is iteration in programming?", "Repeating a block of code", ["A one-off print", "Repeating a block of code", "A network protocol", "A file format"]),
  tq("th56", "2.2", "What is casting?", "Converting between data types", ["Deleting variables", "Converting between data types", "Drawing graphics", "Sending email"]),
  tq("th57", "2.3", "NAND gate output when both inputs are 1?", "0", ["1", "0", "2", "Both"]),
  tq("th58", "2.4", "What is Unicode?", "A character set supporting many languages", ["A CPU brand", "A character set supporting many languages", "A cable", "A virus"]),
  tq("th59", "1.1", "What is parallel processing?", "Multiple processors working at the same time", ["One slow CPU", "Multiple processors working at the same time", "No storage", "Only ROM"]),
  tq("th60", "2.2", "What is a syntax error?", "Code that breaks language rules", ["Slow internet", "Code that breaks language rules", "Full disk", "Weak password"]),
];

const PROG_BANK = [
  pq("ph01", "2.2", "Print numbers 1 to 5 with a for loop.", "for i in range(1, 6):\n    print(i)\n"),
  pq("ph02", "2.2", "Ask for a name and print Hello plus the name.", 'name = input("Name: ")\nprint("Hello", name)\n'),
  pq("ph03", "2.1", "Print the largest value in [3, 7, 2].", "print(max([3, 7, 2]))\n"),
  pq("ph04", "2.2", "Check if a number is even or odd.", 'n = int(input("Number: "))\nprint("Even" if n % 2 == 0 else "Odd")\n'),
  pq("ph05", "2.2", "Print sum of two integers from input.", 'print(int(input("A: ")) + int(input("B: ")))\n'),
  pq("ph06", "2.2", "Print a 5-star triangle (one star per line).", 'for i in range(1, 6):\n    print("*" * i)\n'),
  pq("ph07", "2.2", "Count from 10 down to 1.", "for n in range(10, 0, -1):\n    print(n)\n"),
  pq("ph08", "2.2", "Ask age; print Adult if 18+ else Minor.", 'age = int(input("Age: "))\nprint("Adult" if age >= 18 else "Minor")\n'),
  pq("ph09", "2.1", "Print each item in list ['a','b','c'].", "for x in ['a','b','c']:\n    print(x)\n"),
  pq("ph10", "2.2", "Print square of numbers 1-5.", "for i in range(1, 6):\n    print(i * i)\n"),
  pq("ph11", "2.2", "Ask password; print Granted if equals 'gcse'.", 'if input("Pwd: ") == "gcse":\n    print("Granted")\n'),
  pq("ph12", "2.2", "Print average of [10, 20, 30].", "nums = [10, 20, 30]\nprint(sum(nums)/len(nums))\n"),
  pq("ph13", "2.1", "Linear search: find 7 in [2,5,7,1].", "nums = [2,5,7,1]\nfor n in nums:\n    if n == 7:\n        print('Found')\n"),
  pq("ph14", "2.2", "Print multiplication table for 3 (1-5).", "for i in range(1, 6):\n    print(3 * i)\n"),
  pq("ph15", "2.2", "Ask two numbers; print greater.", 'a,b=int(input()),int(input())\nprint(max(a,b))\n'),
  pq("ph16", "2.2", "Print FizzBuzz 1-15 (Fizz / Buzz / FizzBuzz).", ""),
  pq("ph17", "2.2", "Store 5 names in a list; print first and last.", "names = ['a','b','c','d','e']\nprint(names[0], names[-1])\n"),
  pq("ph18", "2.2", "Print total of scores entered until -1.", ""),
  pq("ph19", "2.1", "Sort [4,1,9] and print result.", "print(sorted([4,1,9]))\n"),
  pq("ph20", "2.2", "Print reverse of string 'gcse'.", "print('gcse'[::-1])\n"),
  pq("ph21", "2.2", "Ask mark; print Pass if >= 50.", 'm=int(input("Mark: "))\nprint("Pass" if m>=50 else "Fail")\n'),
  pq("ph22", "2.2", "Print characters in 'Python' one per line.", "for c in 'Python':\n    print(c)\n"),
  pq("ph23", "2.2", "Count vowels in input word.", ""),
  pq("ph24", "2.1", "Print index and value for list [10,20,30].", "for i,v in enumerate([10,20,30]):\n    print(i,v)\n"),
  pq("ph25", "2.2", "Print Celsius to Fahrenheit for 0,10,20.", "for c in [0,10,20]:\n    print(c*1.8+32)\n"),
  pq("ph26", "2.2", "Ask how many times; print Hello that many times.", ""),
  pq("ph27", "2.2", "Print True if list contains 5.", "print(5 in [1,2,3,4,5])\n"),
  pq("ph28", "2.2", "Build string from list ['X','e','n'].", "print(''.join(['X','e','n']))\n"),
  pq("ph29", "2.1", "Print min and max of random list.", "nums=[3,8,1,6]\nprint(min(nums), max(nums))\n"),
  pq("ph30", "2.2", "Print double each value in [1,2,3].", "for n in [1,2,3]:\n    print(n*2)\n"),
  pq("ph31", "2.2", "Ask username; validate length >= 3.", ""),
  pq("ph32", "2.2", "Print sum 1..10 using while.", "t,n=0,1\nwhile n<=10:\n t+=n; n+=1\nprint(t)\n"),
  pq("ph33", "2.2", "Print nested loop coordinates 1-3.", "for x in range(1,4):\n  for y in range(1,4):\n    print(x,y)\n"),
  pq("ph34", "2.1", "Count occurrences of 'a' in 'banana'.", "print('banana'.count('a'))\n"),
  pq("ph35", "2.2", "Print absolute value of -7.", "print(abs(-7))\n"),
  pq("ph36", "2.2", "Ask item price; print with 20% VAT.", ""),
  pq("ph37", "2.2", "Print whether year is leap (simplified).", ""),
  pq("ph38", "2.1", "Merge two lists and print.", "print([1,2]+[3,4])\n"),
  pq("ph39", "2.2", "Print table of squares 1-10 formatted.", ""),
  pq("ph40", "2.2", "Simulate dice roll 1-6 and print.", "import random\nprint(random.randint(1,6))\n"),
  pq("ph41", "2.2", "Ask sentence; print word count.", ""),
  pq("ph42", "2.2", "Print factors of 12.", ""),
  pq("ph43", "2.1", "Binary search outline on sorted list.", ""),
  pq("ph44", "2.2", "Print initials from full name input.", ""),
  pq("ph45", "2.2", "Menu loop until user chooses quit.", ""),
  pq("ph46", "2.2", "Print grade from mark thresholds.", ""),
  pq("ph47", "2.2", "Remove duplicates from list print.", "print(list(set([1,2,2,3])))\n"),
  pq("ph48", "2.2", "Print factorial of 5.", "f=1\nfor i in range(1,6): f*=i\nprint(f)\n"),
  pq("ph49", "2.2", "Write function greet and call it.", "def greet():\n    print('Hi')\ngreet()\n"),
  pq("ph50", "2.2", "Read file lines count (pseudo).", "# open file and count lines\n"),
  pq("ph51", "2.2", "Print numbers 1-10 on one line.", "print(' '.join(str(i) for i in range(1,11)))\n"),
  pq("ph52", "2.2", "Ask temperature C; print F.", 'c=float(input("C: "))\nprint(c*1.8+32)\n'),
  pq("ph53", "2.2", "Print whether list is empty.", "nums=[]\nprint('empty' if not nums else 'has data')\n"),
  pq("ph54", "2.2", "Print index of 'x' in list or -1.", "print(['a','b'].index('x') if 'x' in ['a','b'] else -1)\n"),
  pq("ph55", "2.1", "Print bubble sort pass (one swap).", ""),
  pq("ph56", "2.2", "Validate integer input in range 1-10.", ""),
  pq("ph57", "2.2", "Print palindrome check for word.", ""),
  pq("ph58", "2.2", "Store dict of scores and print highest key.", "s={'a':3,'b':9}\nprint(max(s,key=s.get))\n"),
  pq("ph59", "2.2", "Print comma-separated even numbers 2-20.", "print(','.join(str(i) for i in range(2,21,2)))\n"),
  pq("ph60", "2.2", "Function area of rectangle w,h.", "def area(w,h):\n    return w*h\nprint(area(4,5))\n"),
];

function chunkBank(bank, index, size = 10) {
  const start = index * size;
  return bank.slice(start, start + size);
}

const THEORY_META = [
  { title: "Theory Mock 1", subtitle: "CPU & systems architecture" },
  { title: "Theory Mock 2", subtitle: "Memory & storage" },
  { title: "Theory Mock 3", subtitle: "Networks" },
  { title: "Theory Mock 4", subtitle: "Security & ethics" },
  { title: "Theory Mock 5", subtitle: "Algorithms & logic" },
  { title: "Theory Mock 6", subtitle: "Programming concepts" },
];

const PROG_META = [
  { title: "Programming Mock 1", subtitle: "Loops & output" },
  { title: "Programming Mock 2", subtitle: "Input & decisions" },
  { title: "Programming Mock 3", subtitle: "Lists & strings" },
  { title: "Programming Mock 4", subtitle: "Searching & sorting" },
  { title: "Programming Mock 5", subtitle: "Functions & practice" },
  { title: "Programming Mock 6", subtitle: "Mixed GCSE tasks" },
];

export const MOCK_TESTS = [
  ...THEORY_META.map((meta, i) => ({
    id: `theory-mock-${i + 1}`,
    type: "theory",
    ...meta,
    questionCount: 10,
    questions: chunkBank(THEORY_BANK, i, 10),
  })),
  ...PROG_META.map((meta, i) => ({
    id: `prog-mock-${i + 1}`,
    type: "programming",
    ...meta,
    questionCount: 10,
    questions: chunkBank(PROG_BANK, i, 10),
  })),
];

export function getMockTestById(testId) {
  return MOCK_TESTS.find((t) => t.id === testId) || null;
}
