export const GCSE_QUESTIONS = [
  "Write pseudocode for checking if a number is even.",
  "Write pseudocode for finding the larger of two numbers.",
  "Write pseudocode for a count-controlled loop from 1 to 10.",
  "Write pseudocode for validating input between 1 and 100.",
  "Create pseudocode for summing values in a list.",
  "Create pseudocode for finding the minimum value in a list.",
  "Create pseudocode for linear search in an array.",
  "Create pseudocode for binary search in a sorted array.",
  "Create pseudocode for bubble sort.",
  "Create pseudocode for insertion sort.",
  "Explain what this line does: x = x + 1.",
  "Explain what this line does: total += price.",
  "Fix this bug: if score = 10:",
  "Fix this bug: for i in range(10) print(i)",
  "Fix this bug: print('Hello)",
  "Fix this bug: numbers[5] when list has 3 items.",
  "Explain why indentation matters in Python.",
  "Write a Python function that returns the square of a number.",
  "Write a Python function that returns True if number is prime.",
  "Write a Python function to reverse a string.",
  "Write a Python function to count vowels in a word.",
  "Write a Python function to calculate factorial.",
  "Write a Python function to find the largest number in a list.",
  "Write a Python function to find the smallest number in a list.",
  "Write a Python function to compute average of a list.",
  "Write a Python function that checks if a string is palindrome.",
  "Write a loop to print numbers 1 to 20.",
  "Write a loop to print only even numbers from 1 to 20.",
  "Write a loop that counts down from 10 to 1.",
  "Write a while loop that repeats until user types 'quit'.",
  "Use an if statement to classify grade A/B/C.",
  "Use if-elif-else to classify age groups.",
  "Write code to check if username length is at least 6.",
  "Write code to validate password length is at least 8.",
  "Write code to ensure input is numeric.",
  "Use try/except to handle invalid integer input.",
  "Use try/except to handle division by zero.",
  "Write a list of five student names and print each one.",
  "Append three new values into a list and print result.",
  "Remove a value from a list safely.",
  "Sort a list in ascending order.",
  "Sort a list in descending order.",
  "Slice a list to get first three elements.",
  "Use list comprehension to create squares 1-10.",
  "Create a dictionary with name, age, class.",
  "Read a value from dictionary by key.",
  "Update a dictionary value by key.",
  "Loop through dictionary keys and values.",
  "What output does len('xenon') give?",
  "What output does 'abc'.upper() give?",
  "What output does 'HELLO'.lower() give?",
  "What output does 'py' * 3 give?",
  "What output does 7 // 2 give?",
  "What output does 7 % 2 give?",
  "What output does bool(0) give?",
  "What output does bool('text') give?",
  "Trace this code: x=3; x*=2; print(x).",
  "Trace this code: a=5; b=2; print(a-b).",
  "Trace this code: nums=[1,2,3]; print(nums[-1]).",
  "Trace this code: print(range(3)). What issue do you see?",
  "Correct this: if name == 'Sam' or 'Tom':",
  "Correct this: while x < 10 x += 1",
  "Correct this: def add(a,b) return a+b",
  "Correct this: list = [1,2,3]; print(list(5))",
  "Explain difference between == and = in Python.",
  "Explain difference between list and tuple.",
  "Explain difference between parameter and argument.",
  "Explain difference between for and while loops.",
  "Explain when to use a function.",
  "Explain what return does in a function.",
  "Explain global vs local variable in simple terms.",
  "Write a function with two parameters and return their sum.",
  "Write a function that takes list and returns count of even numbers.",
  "Write a function that takes sentence and returns word count.",
  "Write a function that returns first character of string.",
  "Write a function that returns last character of string.",
  "Write a menu program with 3 options using while loop.",
  "Write a quiz program that asks 3 questions.",
  "Write a score tracker that adds points for correct answers.",
  "Write code to store 5 test scores and print average.",
  "Write code to count how many scores are above 50.",
  "Write code to find highest and lowest score.",
  "Write code to convert Celsius to Fahrenheit.",
  "Write code to convert Fahrenheit to Celsius.",
  "Write code that checks if year is leap year.",
  "Write code that checks if number is positive, negative or zero.",
  "Write code that swaps two variable values.",
  "Write code that removes duplicates from list.",
  "Write code that joins list of words into sentence.",
  "Write code that splits sentence into words.",
  "Write code that counts frequency of each character in a string.",
  "Write code that counts frequency of each word in a sentence.",
  "Write code to generate first 10 Fibonacci numbers.",
  "Write code to test if number is in a list.",
  "Write code to print multiplication table for number n.",
  "Write code to read text file and count lines.",
  "Write code to write three lines into a text file.",
  "Write code to safely open a file using with statement.",
  "Write code to handle FileNotFoundError.",
  "Design a small Python program for a GCSE revision timer.",
  "Design a small Python program for simple to-do list.",
];
